---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Заказанные товары должны удаляться из корзины
  - При перезагрузке страницы не должен меняться язык сайта
  - В списке категорий должны отображаться все имеющиеся категории
  - При нажатии на кнопку "Магазин" в хедере должна открываться главная страница сайта
  - Категории и описание товара должны быть на выбранном языке сайта
  - При оформлении заказа пользователь должен иметь возможность выбрать удобный вариант оплаты и доставки товара
  - В поиске по цене нельзя вводить отрицательные числа
  - В карточке товара и каталоге должны отображаться название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность продолжать выбирать товары в каталоге после добавления товара в корзину
  - Корзина должна храниться в сессии браузера
